### ISSUE TITLE
Term Reference fields?

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/entityreference_migration#1]
Does this or will this work with Term Reference fields?

**Comment by laryn** [comment]
For reference: https://forum.backdropcms.org/forum/convert-term-reference-entity-reference-field

> The Readme doesn't mention it but the issue below suggests it may work:
> - https://www.drupal.org/project/entityreference_migration/issues/1681908

**Comment by indigoxela** [comment]
I don't think term ref fields are considered at all (looking at the code)

```
  if (!in_array($field_info['type'], array('node_reference', 'user_reference'))) {
    drupal_set_message(t("Field @field is not a references field.", array('@field' => $field_name)), 'error');
  }
```
BTW "drupal_set_message..." - really? :stuck_out_tongue:

**Comment by herbdool** [comment]
@stpaultim done
