### ISSUE TITLE
Error due to Table cache_entity_rules_config doesn't exist

### ISSUE THREAD

**Issue by kswan** [backdrop-contrib/entityreference_migration#3]
I get this error when I attempt to run the migration.
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'db-dev.cache_entity_rules_config' doesn't exist: TRUNCATE {cache_entity_rules_config} ; Array ( ) in cache_flush() (line 141 of /site-8080/core/includes/cache.inc).

My database doesn't have a cache_entity_rules_config table.

It is curious that the error is in a core function, but I can run the "Flush all caches" with no errors.

**Comment by kswan** [comment]
I found the problem:
https://github.com/backdrop-contrib/entityreference_migration/blob/e62b48af14681b2ce113a6383b6816457213f978/entityreference_migration.module#L117-L119

![image](https://user-images.githubusercontent.com/154391/209411739-e03128ba-cf4c-4965-9a20-9c7359bcc288.png)

There are cache tables for each of the entity types except rules_config.

I think entityreference_migration needs a check for "entity cache" before running the cache_flush() function.

**Comment by kswan** [comment]
I found that backdrop_flush_all_caches() builds the list of cached entities using entity_flush_caches() which properly checks the "entity cache" value for each entity.

**Comment by keiserjb** [comment]
I had s similar problem with menu caches.  PR fixed it.

**Comment by kswan** [comment]
@herbdool Have you had a chance to look at this PR? Any chance we can get a release with the PR applied?

**Comment by herbdool** [comment]
I was thinking of being more "surgical" in clearing caches so it's not everything on the site, but it's not that big a deal. Someone will only use the module once likely. Thanks @kswan.
